version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@3.0.0
  aws-cli: circleci/aws-cli@0.1.9
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0

executors:
  docker-python:
    docker:
      - image: circleci/python:3.8
  docker-terraform:
    docker:
      - image: hashicorp/terraform:1.5.7

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  assume-role-and-persist-workspace:
    description: "Assumes deployment role and persists credentials across jobs"
    parameters:
      aws-account:
        type: string
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: <<parameters.aws-account>>
          profile_name: default
          role: "LBH_Circle_CI_Deployment_Role"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  terraform-init-then-plan:
    description: "Initializes and run plan from terraform configuration"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform get -update=true
            terraform init
          name: get and init
      - run:
          name: plan
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform plan -out=plan.out
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
            - project/*
  terraform-apply:
    description: "Runs Terraform Apply"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          name: apply & save ecr repo URL
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform apply -auto-approve plan.out

            echo "export ECR_REPO_URL=$(terraform output -raw ecr_repository_url)" >> $BASH_ENV
            cp $BASH_ENV ~/bash.env
      - run:
          name: verify bash.env
          command: cat ~/bash.env
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
            - bash.env

jobs:
  build_and_test:
    working_directory: ~/report_a_defect
    docker:
      - image: cimg/base:2025.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run the tests
          command: |
            bin/dtest-server ci
            bin/dspec
      - run:
          name: Save the tested Docker image for deployment
          command: |
            docker image tag report_a_defect-test:latest reportadefect:$CIRCLE_SHA1
            docker image save -o /tmp/built-image.tar reportadefect:$CIRCLE_SHA1
            docker image load --input /tmp/built-image.tar
      - run:
          name: Save the application for deployment
          command: |
            cp -rT . /tmp/report-a-defect
      - save_cache:
          key: docker-images-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /tmp/report-a-defect
            - /tmp/built-image.tar
  assume-role-development:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_DEVELOPMENT
  assume-role-staging:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_STAGING
  assume-role-production:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_PRODUCTION
  terraform-init-and-plan-development:
    executor: docker-terraform
    steps:
      - terraform-init-then-plan:
          environment: "development"
  terraform-apply-development:
    executor: docker-terraform
    steps:
      - terraform-apply:
          environment: "development"
  terraform-init-and-plan-staging:
    executor: docker-terraform
    steps:
      - terraform-init-then-plan:
          environment: "staging"
  terraform-apply-staging:
    executor: docker-terraform
    steps:
      - terraform-apply:
          environment: "staging"
  terraform-init-and-plan-production:
    executor: docker-terraform
    steps:
      - terraform-init-then-plan:
          environment: "production"
  terraform-apply-production:
    executor: docker-terraform
    steps:
      - terraform-apply:
          environment: "production"
  deploy-development:
    working_directory: ~/report_a_defect
    docker:
      - image: cimg/base:2025.04
    steps:
      - *attach_workspace
      - restore_cache:
          keys:
            - docker-images-{{ .Environment.CIRCLE_SHA1 }}
      - setup_remote_docker
      - run:
          name: Install Python
          command: |
            sudo apt update
            sudo apt install software-properties-common
            sudo add-apt-repository --yes ppa:deadsnakes/ppa
            sudo apt install python3-pip
      - run:
          name: Install AWS CLI
          command: pip3 install awscli --upgrade --user
      - run:
          name: Load environment variables
          command: |
            cat ~/bash.env >> $BASH_ENV
      - run:
          name: Login to ECR
          command: |
            export AWS_REGION=eu-west-2
            export AWS_ACCOUNT=$(aws sts get-caller-identity --query "Account" --output text)
            docker login -u AWS -p $(aws ecr get-login-password --region eu-west-2) $AWS_ACCOUNT.dkr.ecr.eu-west-2.amazonaws.com
      - run:
          name: Tag new image for development release
          command: |
            docker image load --input /tmp/built-image.tar
            docker tag reportadefect:$CIRCLE_SHA1 $ECR_REPO_URL:$CIRCLE_SHA1
            docker tag reportadefect:$CIRCLE_SHA1 $ECR_REPO_URL:latest
            docker tag reportadefect:$CIRCLE_SHA1 $ECR_REPO_URL:development
      - run:
          name: Release new image to ECR
          command: |
            docker push $ECR_REPO_URL:$CIRCLE_SHA1
            docker push $ECR_REPO_URL:latest
            docker push $ECR_REPO_URL:development
  deploy_staging:
    working_directory: ~/report_a_defect
    docker:
      - image: cimg/base:2025.04
    steps:
      - restore_cache:
          keys:
            - docker-images-{{ .Environment.CIRCLE_SHA1 }}
      - setup_remote_docker
      - run:
          name: Login to Docker
          command: echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
      - run:
          name: Setup Heroku CLI
          command: |
            cd /tmp/report-a-defect
            chmod +x .circleci/setup-heroku.sh
            .circleci/setup-heroku.sh
      - run:
          name: Deploy the Docker image to Heroku Staging
          command: |
            docker image load --input /tmp/built-image.tar
            docker tag reportadefect:$CIRCLE_SHA1 registry.heroku.com/$HEROKU_APP_NAME_STAGING/web
            docker push registry.heroku.com/$HEROKU_APP_NAME_STAGING/web
            heroku container:release web --app $HEROKU_APP_NAME_STAGING
            heroku container:release worker --app $HEROKU_APP_NAME_STAGING

  deploy_production:
    working_directory: ~/report_a_defect
    docker:
      - image: cimg/ruby:3.1.0
    steps:
      - restore_cache:
          keys:
            - docker-images-{{ .Environment.CIRCLE_SHA1 }}
      - setup_remote_docker
      - run:
          name: Login to Docker
          command: docker login --username=_ --password-stdin=$HEROKU_API_KEY registry.heroku.com
      - run:
          name: Setup Heroku
          command: |
            cd /tmp/report-a-defect
            chmod +x .circleci/setup-heroku.sh
            .circleci/setup-heroku.sh
      - run:
          name: Deploy the Docker image to Heroku Production
          command: |
            docker image load --input /tmp/built-image.tar
            docker tag reportadefect:$CIRCLE_SHA1 registry.heroku.com/$HEROKU_APP_NAME_PRODUCTION/web
            docker push registry.heroku.com/$HEROKU_APP_NAME_PRODUCTION/web
            heroku container:release web --app $HEROKU_APP_NAME_PRODUCTION
            heroku container:release worker --app $HEROKU_APP_NAME_STAGING

workflows:
  version: 2
  check-and-deploy-development:
    jobs:
      - build_and_test
      - assume-role-development:
          context: api-assume-role-housing-development-context
          requires:
            - build_and_test
      - terraform-init-and-plan-development:
          requires:
            - assume-role-development
      - terraform-apply-development:
          requires:
            - terraform-init-and-plan-development
      - deploy-development:
          requires:
            - terraform-apply-development
  continuous_delivery:
    jobs:
      - build_and_test:
          filters:
            branches:
              only:
                - develop
                - master
      - deploy_staging:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - develop
      - deploy_production:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - master
