NBT_GROUP_EMAIL = ENV['NBT_GROUP_EMAIL']

NOTIFY_KEY = ENV['NOTIFY_KEY']
NOTIFY_FORWARD_DEFECT_TEMPLATE = ENV['NOTIFY_FORWARD_DEFECT_TEMPLATE']
NOTIFY_DAILY_DUE_SOON_TEMPLATE = ENV['NOTIFY_DAILY_DUE_SOON_TEMPLATE']
NOTIFY_DAILY_ESCALATION_TEMPLATE = ENV['NOTIFY_DAILY_ESCALATION_TEMPLATE']
